'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const catalog=require('../assets/public/catalog.js');
const source=fs.readFileSync(path.join(__dirname,'../assets/public/hero-motion.js'),'utf8');
function setup(reduced=false){
  const events={},wall={innerHTML:''};
  const button={hidden:true,attrs:{},setAttribute(k,v){this.attrs[k]=v;},addEventListener(k,fn){events[k]=fn;}};
  const hero={dataset:{},querySelector:s=>s==='[data-motion-columns]'?wall:button};
  const media={matches:reduced,addEventListener(k,fn){events.media=fn;}};
  const document={readyState:'complete',hidden:false,querySelector:()=>hero,addEventListener(k,fn){events[k]=fn;}};
  const ctx={document,IntersectionObserver:function(fn){events.intersection=fn;this.observe=()=>{};},window:{PagasiCatalog:catalog,PagasiSite:{escape:String,icon:()=>'',fitPhotos(){}},matchMedia:()=>media}};
  vm.runInNewContext(source,ctx);
  return {hero,button,wall,media,document,events};
}
const t=setup();
assert.equal(t.hero.dataset.motionRunning,'true');
t.events.click();
assert.equal(t.hero.dataset.motionRunning,'false');
assert.equal(t.button.attrs['aria-pressed'],'true');
t.events.intersection([{isIntersecting:false}]);
t.events.intersection([{isIntersecting:true}]);
t.document.hidden=true;t.events.visibilitychange();
t.document.hidden=false;t.events.visibilitychange();
assert.equal(t.hero.dataset.motionRunning,'false','user pause survives visibility changes');
t.events.click();
assert.equal(t.hero.dataset.motionRunning,'true');
t.events.intersection([{isIntersecting:false}]);
assert.equal(t.hero.dataset.motionRunning,'false');
t.events.intersection([{isIntersecting:true}]);
assert.equal(t.hero.dataset.motionRunning,'true');
t.document.hidden=true;t.events.visibilitychange();
assert.equal(t.hero.dataset.motionRunning,'false');
t.document.hidden=false;t.events.visibilitychange();
assert.equal(t.hero.dataset.motionRunning,'true');
console.log('OK pause/resume and offscreen/background suspension preserve user choice');
const r=setup(true);
assert.equal(r.hero.dataset.motionRunning,'false');
assert.equal(r.button.hidden,true);
r.media.matches=false;r.events.media();
assert.equal(r.hero.dataset.motionRunning,'true');
r.events.click();
r.media.matches=true;r.events.media();
r.media.matches=false;r.events.media();
assert.equal(r.hero.dataset.motionRunning,'false','preference change must not override manual pause');
console.log('OK reduced-motion preference respected initially and when changed');
const ids=[...t.wall.innerHTML.matchAll(/data-motion-model="(\d+)"/g)].map(m=>Number(m[1]));
assert.equal(ids.length,24);
assert.equal(new Set(ids).size,12);
for(const id of new Set(ids))assert.equal(ids.filter(x=>x===id).length,2);
for(const src of [...t.wall.innerHTML.matchAll(/(?:src|srcset)="([^"]+)"/g)].map(x=>x[1]))assert.ok(fs.existsSync(path.join(__dirname,'..',src)),src);
assert.ok(!t.wall.innerHTML.includes('<a '),'decorative wall must not add hidden focusable links');
console.log('OK 12 real models, duplicated for looping, with valid original and optimized photos');
